namespace VoxelCraft.Core
{
    /// <summary>All block ids. Stored as byte in chunks; do not reorder existing entries.</summary>
    public enum BlockType : byte
    {
        Air = 0,
        Grass = 1,
        Dirt = 2,
        Stone = 3,
        Sand = 4,
        Log = 5,
        Leaves = 6,
        Water = 7,
        Plank = 8,
        Cobble = 9,
        Glass = 10,
        Snow = 11,
        Brick = 12,
        Bedrock = 13,
        CoalOre = 14,
        IronOre = 15,
        GoldOre = 16,
        DiamondOre = 17,
        Gravel = 18,
        Ice = 19,
        Obsidian = 20,
        MossyCobble = 21,
        StoneBrick = 22,
        Wheat0 = 23,
        Wheat1 = 24,
        Wheat2 = 25,
        Wheat3 = 26,
        Glowstone = 27,
        Path = 28,
        WoolWhite = 29,
        WoolRed = 30,
        WoolYellow = 31,
        WoolBlue = 32,
        WoolGreen = 33,
        WoolBlack = 34,
        Torch = 35,
        DoorClosed = 36,
        DoorOpen = 37,
        Chest = 38,
        BedFoot = 39,
        BedHead = 40,
        Fence = 41,
        Furnace = 42,
        /// <summary>Rail: spans Z when the neighbouring solid is on ±X (placed on the block grid, flat).</summary>
        Rail = 43,
        /// <summary>Rail oriented along X.</summary>
        RailX = 44,
    }
}
